# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: ".:: Francesco Vozza's Home ::"
# subtitle: "No non-sense, pragmatic manager with a track record of building highly motivated teams delivering high quality software and services."
email:
description: >- # this means to ignore newlines until "baseurl:"
  Francesco Vozza personal web site
repository: "fvozza/vozza.io"
# twitter_username: fvozza
github_username: fvozza
minimal_mistakes_skin: default
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: Europe/Berlin

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
  - jekyll-pdf-embed

author:
  name   : "Francesco Vozza"
  avatar : "/assets/images/profile.jpg"
  bio    : "Rusty coder, pragmatic engineering manager, seriously in love with food. Living in Berlin. Proudly from Puglia."
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://blog.vozza.io"
    - label: "Linkedin"
      icon: "fab fa-fw fa-linkedin" # https://fontawesome.com/icons
      url: "https://www.linkedin.com/in/francescovozza/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/fvozza"

# footer:
#   links:
#     - label: "GitHub"
#       icon: "fab fa-fw fa-github"
#       url: "https://github.com/"

atom_feed:
  hide: true

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: false
      related: false
      show_date: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
